### ISSUE TITLE
TypeError: tuple indices must be integers, not str

### ISSUE THREAD

**Issue by tdhopper** [sentience/HyperlinkHelper#12]
Trying to use the Wikipedia linker in ST2 on Windows. I get this error (every time, I believe).

```
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 362, in run_
    return self.run(edit)
  File ".\link_to_wikipedia_page_for_selection.py", line 67, in run
    link = self.get_link_with_title(txt)
  File ".\link_to_wikipedia_page_for_selection.py", line 35, in get_link_with_title
    decoded_content = content.decode(chardet.detect(content)['encoding'])
  File "C:\Users\thopper\AppData\Roaming\Sublime Text 2\Packages\HyperlinkHelper\chardet\__init__.py", line 24, in detect
    u.feed(aBuf)
  File "C:\Users\thopper\AppData\Roaming\Sublime Text 2\Packages\HyperlinkHelper\chardet\universaldetector.py", line 116, in feed
    if prober.feed(aBuf) == constants.eFoundIt:
  File "C:\Users\thopper\AppData\Roaming\Sublime Text 2\Packages\HyperlinkHelper\chardet\charsetgroupprober.py", line 60, in feed
    st = prober.feed(aBuf)
  File "C:\Users\thopper\AppData\Roaming\Sublime Text 2\Packages\HyperlinkHelper\chardet\utf8prober.py", line 53, in feed
    codingState = self._mCodingSM.next_state(c)
  File "C:\Users\thopper\AppData\Roaming\Sublime Text 2\Packages\HyperlinkHelper\chardet\codingstatemachine.py", line 44, in next_state
    byteCls = self._mModel['classTable'][c]
TypeError: tuple indices must be integers, not str
```

**Comment by DouaeAhmadoun** [comment]
Hi @sentience
I have the same bug. Can you help me to solve it?

**Comment by sentience** [comment]
@DouaeAhmadoun Can you confirm what versions of Sublime Text and HyperlinkHelper you are seeing the problem with?
